apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk060-sample-app
  labels:
    app: sk060-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk060-sample-app
  template:
    metadata:
      labels:
        app: sk060-sample-app
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: sk060-sample-app
          image: amdp-registry.skala-ai.com/skala26a-ai2/sk060-sample-app:latest
          ports:
            - containerPort: 8080