apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sk060-sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chaeyh4//sk060-skala3.git
    targetRevision: main
    path: sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true